---
- name: RSHINY | Get current RShiny version
  command: "shiny-server version"
  register: rshiny_version_current
  changed_when: false
  failed_when: false

- block:

  - name: RSHINY | Download RShiny-Server
    get_url:
      url: https://download3.rstudio.org/centos7/x86_64/shiny-server-{{ rshiny_version }}-x86_64.rpm
      dest: /tmp/shiny-server-{{ rshiny_version }}-x86_64.rpm
      mode: 0644

  - name: RSHINY | Install RShiny-Server
    dnf:
      name: /tmp/shiny-server-{{ rshiny_version }}-x86_64.rpm
      disable_gpg_check : yes
      state: present

  - name: RSHINY | Remove installer
    file:
      path: /tmp/rshiny-{{ rshiny_version }}-x86_64.rpm
      state: absent

  - name: RSHINY | Make sure RShiny-Server is started
    service:
      name: shiny-server
      enabled: true
      state: started

  when: "rshiny_version | string not in rshiny_version_current|string"

- name: RSHINY | Download ShinyCannon
  get_url:
    url: https://github.com/rstudio/shinycannon/releases/download/v1.1.0/shinycannon-1.1.0-45731f0.x86_64.rpm
    dest: /tmp/shinycannon.rpm
    mode: 0644

- name: RSHINY | Install ShinyCannon
  dnf:
    name: /tmp/shinycannon.rpm
    disable_gpg_check : yes
    state: present